
TVL2_WTHRESH_1		= 1;
TVL2_WTHRESH_2		= 2;
TVL2_WMIL_1		= 3;
TVL2_WMIL_2		= 4;
TVL2_SB_1		= 5;

TVL2_CELLNAMES{TVL2_WTHRESH_1} = 'IRN Adapt Thr';
TVL2_CELLNAMES{TVL2_WTHRESH_2} = 'IRN Adapt Thr/PCG';
TVL2_CELLNAMES{TVL2_WMIL_1} = 'MIL Adapt PCG';
TVL2_CELLNAMES{TVL2_WMIL_2} = 'MIL Fixed PCG';
TVL2_CELLNAMES{TVL2_SB_1} = 'ADMM Fixed gamma';

% ======================================

TVL1_WTHRESH_SUB_1	= 1;
TVL1_WTHRESH_SUB_2	= 2;
TVL1_WTHRESH_1		= 3;
TVL1_WTHRESH_2		= 4;
TVL1_WMIL_1		= 5;
TVL1_WMIL_2		= 6;
TVL1_SB_1		= 7;

TVL1_CELLNAMES{TVL1_WTHRESH_SUB_1} = 'Sub Adapt Thr';
TVL1_CELLNAMES{TVL1_WTHRESH_SUB_2} = 'Sub Adapt Thr/PCG';
TVL1_CELLNAMES{TVL1_WTHRESH_1} = 'IRN Adapt Thr';
TVL1_CELLNAMES{TVL1_WTHRESH_2} = 'IRN Adapt Thr/PCG';
TVL1_CELLNAMES{TVL1_WMIL_1} = 'MIL Adapt PCG';
TVL1_CELLNAMES{TVL1_WMIL_2} = 'MIL Fixed PCG';
TVL1_CELLNAMES{TVL1_SB_1} = 'ADMM Fixed gamma';


