% This is used to set the evaluation metrics that to be computed
%
% Author:Xingchen Zhang, Ping Ye, Gang Xiao
% Contact: xingchen.zhang@imperial.ac.uk

function metrics=configMetrics

 metricVIFB={struct('name','Avg_gradient'),...
     struct('name','Cross_entropy'),...
     struct('name','Edge_intensity'),...
     struct('name','Entropy'),...
     struct('name','Mutinf'),...
     struct('name','Psnr'),...
     struct('name','Qabf'),...
     struct('name','Qcb'),...
     struct('name','Qcv'),...  
     struct('name','Rmse'),...
     struct('name','Spatial_frequency'),...
     struct('name','Ssim'),...
     struct('name','Variance'),...
     };

 metrics = [metricVIFB];
