% This is used to set the VIF algorithms that to be run 
%
% Author:Xingchen Zhang, Ping Ye, Gang Xiao
% Contact: xingchen.zhang@imperial.ac.uk


function methods=configMethods

 methodVIFB={struct('name','ADF'),...
        struct('name','CBF'),...
        struct('name','CNN'),...             
        struct('name','DLF'),...
        struct('name','FPDE'),...
        struct('name','GFCE'),...
        struct('name','GFF'),...
        struct('name','GTF'),...
        struct('name','HMSD_GF'),...
        struct('name','Hybrid_MSD'),...
        struct('name','IFEVIP'),...
        struct('name','LatLRR'),...
        struct('name','LP_SR'),...
        struct('name','MGFF'),...        
        struct('name','MSVD'),...     
        struct('name','NSCT_SR'),... 
        struct('name','ResNet'),...
        struct('name','RP_SR'),...
        struct('name','TIF'),...
        struct('name','VSMWLS'),...
        struct('name','IFCNN'),...
        struct('name','SeAFusion'),...
        struct('name','SwinFusion'),...
        struct('name','U2Fusion'),...
        struct('name','YDTR'),...
     };
       
methods = [methodVIFB];
